include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: false
    public_member_api_docs: false
    sort_pub_dependencies: false


analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**.g.dart'