name: bloc_lint
version: 0.0.0
description: Set of lint rules for the Flutter BLoC library.
repository: https://github.com/vmichalak/bloc_lint
issue_tracker: https://github.com/vmichalak/bloc_lint/issues

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  analyzer: ^6.7.0
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.7.0

dev_dependencies:
  very_good_analysis: ^6.0.0
  test: ^1.25.8
