name: bloc_lint

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: '3.5.1'

      - name: Get dependencies
        run: dart pub get

      - name: Test lint rules
        run: cd example && dart run custom_lint && cd ..